[package]
name = "wit-parser"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
logos = "0.13"
thiserror.workspace = true
id-arena = "2.2.1"
miette.workspace = true
distance = "0.4"
log.workspace = true
serde = { workspace = true, features = ["derive"] }
schemars = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4"
serde_json.workspace = true
