[package]
name = "tauri-bindgen-host"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags.workspace = true
tauri-bindgen-host-macro = { path = "../host-macro" }
async-trait = "0.1"
tauri.workspace = true
tracing = { version = "0.1", features = ["log", "log-always"] }
anyhow = "1.0"
serde.workspace = true
ipc-router-wip = { path = "../ipc-router-wip" }
